lfm2_1_2b:
  loader: transformers
  model_id: LiquidAI/LFM2-1.2B
  config:
    model_id: LiquidAI/LFM2-1.2B
    device: auto
    torch_dtype: bfloat16
    use_safetensors: true

qwen3_4b:
  loader: awq
  model_id: Qwen/Qwen3-4B-AWQ
  config:
    model_id: Qwen/Qwen3-4B-AWQ
    device: auto
    torch_dtype: float16

qwen3_1_7b_instruct:
  loader: gptq
  model_id: kaitchup/Qwen3-1.7B-autoround-4bit-gptq
  config:
    model_id: kaitchup/Qwen3-1.7B-autoround-4bit-gptq
    device: auto
    torch_dtype: float16

deepseek_coder_1_3b:
  loader: gptq
  model_id: TheBloke/deepseek-coder-1.3b-instruct-GPTQ
  config:
    model_id: TheBloke/deepseek-coder-1.3b-instruct-GPTQ
    device: auto
    torch_dtype: float16

phi_3_5_mini:
  loader: awq
  model_id: thesven/Phi-3.5-mini-instruct-awq
  config:
    model_id: thesven/Phi-3.5-mini-instruct-awq
    device: auto
    torch_dtype: float16

gemma_2_2b:
  loader: gptq
  model_id: shuyuej/gemma-2-2b-it-GPTQ
  config:
    model_id: shuyuej/gemma-2-2b-it-GPTQ
    device: auto
    torch_dtype: float16

llama_3_2_3b:
  loader: gptq
  model_id: shuyuej/Llama-3.2-3B-Instruct-GPTQ
  config:
    model_id: shuyuej/Llama-3.2-3B-Instruct-GPTQ
    device: auto
    torch_dtype: float16

llama_2_7b_chat:
  loader: gptq
  model_id: TheBloke/Llama-2-7B-Chat-GPTQ
  config:
    model_id: TheBloke/Llama-2-7B-Chat-GPTQ
    device: auto
    torch_dtype: float16

llama3_8b:
  loader: transformers
  model_id: meta-llama/Meta-Llama-3-8B-Instruct
  config:
    model_id: meta-llama/Meta-Llama-3-8B-Instruct
    device: auto
    torch_dtype: float16
    use_safetensors: true

tinyllama_gguf:
  loader: llama_cpp
  model_id: TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF
  config:
    model_path: ./models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
    n_ctx: 4096
    n_gpu_layers: -1
    chat_format: zephyr
    verbose: true
